<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <RootNamespace>Travel_and_Accommodation_Booking_Platform_BackEnd.Application</RootNamespace>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="FluentValidation" Version="12.1.1" />
      <PackageReference Include="MediatR" Version="14.0.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Travel-and-Accommodation-Booking-Platform-BackEnd.Domain\Travel-and-Accommodation-Booking-Platform-BackEnd.Domain.csproj" />
    </ItemGroup>

</Project>
